### ISSUE TITLE
Орфография

### ISSUE THREAD

**Issue by dk721** [bwl-andromeda/bot#1]
drop_db
https://github.com/bwl-andromeda/bot/blob/6e806c57c65ae6d247854a838e3cc1dde0d4cc0b/database/models/engine.py#L18

**Comment by bwl-andromeda** [comment]
В английском языке есть две буквы (d) и (b) , одна звучит как ДИ , другая как БИ. Approve!

**Comment by dk721** [comment]
drob как переводится
